/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresYouzanRouteImport } from './routes/stores.youzan'
import { Route as StoresListRouteImport } from './routes/stores.list'
import { Route as StoresFranchiseesRouteImport } from './routes/stores.franchisees'
import { Route as PurchaseLogisticsRouteImport } from './routes/purchase.logistics'
import { Route as PurchaseJapanParcelRouteImport } from './routes/purchase.japan-parcel'
import { Route as PurchaseJapanBulkRouteImport } from './routes/purchase.japan-bulk'
import { Route as PurchaseDomesticRouteImport } from './routes/purchase.domestic'
import { Route as InventoryTransfersRouteImport } from './routes/inventory.transfers'
import { Route as InventorySkusRouteImport } from './routes/inventory.skus'
import { Route as InventoryProductsRouteImport } from './routes/inventory.products'
import { Route as InventoryInboundRouteImport } from './routes/inventory.inbound'
import { Route as InventoryBatchesRouteImport } from './routes/inventory.batches'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as PurchaseJapanParcelIndexRouteImport } from './routes/purchase.japan-parcel.index'
import { Route as PurchaseDomesticIndexRouteImport } from './routes/purchase.domestic.index'
import { Route as InventorySkusIndexRouteImport } from './routes/inventory.skus.index'
import { Route as InventoryInboundIndexRouteImport } from './routes/inventory.inbound.index'
import { Route as PurchaseJapanParcelNewRouteImport } from './routes/purchase.japan-parcel.new'
import { Route as PurchaseJapanParcelImportRouteImport } from './routes/purchase.japan-parcel.import'
import { Route as PurchaseJapanParcelAccountsRouteImport } from './routes/purchase.japan-parcel.accounts'
import { Route as PurchaseJapanParcelIdRouteImport } from './routes/purchase.japan-parcel.$id'
import { Route as PurchaseDomesticImportRouteImport } from './routes/purchase.domestic.import'
import { Route as PurchaseDomesticIdRouteImport } from './routes/purchase.domestic.$id'
import { Route as InventorySkusIdRouteImport } from './routes/inventory.skus.$id'
import { Route as InventoryInboundNewRouteImport } from './routes/inventory.inbound.new'
import { Route as InventoryInboundIdRouteImport } from './routes/inventory.inbound.$id'
import { Route as ApiPublicMerukiIngestRouteImport } from './routes/api/public/meruki-ingest'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresYouzanRoute = StoresYouzanRouteImport.update({
  id: '/stores/youzan',
  path: '/stores/youzan',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresListRoute = StoresListRouteImport.update({
  id: '/stores/list',
  path: '/stores/list',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresFranchiseesRoute = StoresFranchiseesRouteImport.update({
  id: '/stores/franchisees',
  path: '/stores/franchisees',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseLogisticsRoute = PurchaseLogisticsRouteImport.update({
  id: '/purchase/logistics',
  path: '/purchase/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseJapanParcelRoute = PurchaseJapanParcelRouteImport.update({
  id: '/purchase/japan-parcel',
  path: '/purchase/japan-parcel',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseJapanBulkRoute = PurchaseJapanBulkRouteImport.update({
  id: '/purchase/japan-bulk',
  path: '/purchase/japan-bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseDomesticRoute = PurchaseDomesticRouteImport.update({
  id: '/purchase/domestic',
  path: '/purchase/domestic',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryTransfersRoute = InventoryTransfersRouteImport.update({
  id: '/inventory/transfers',
  path: '/inventory/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySkusRoute = InventorySkusRouteImport.update({
  id: '/inventory/skus',
  path: '/inventory/skus',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryInboundRoute = InventoryInboundRouteImport.update({
  id: '/inventory/inbound',
  path: '/inventory/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryBatchesRoute = InventoryBatchesRouteImport.update({
  id: '/inventory/batches',
  path: '/inventory/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseJapanParcelIndexRoute =
  PurchaseJapanParcelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PurchaseJapanParcelRoute,
  } as any)
const PurchaseDomesticIndexRoute = PurchaseDomesticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchaseDomesticRoute,
} as any)
const InventorySkusIndexRoute = InventorySkusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventorySkusRoute,
} as any)
const InventoryInboundIndexRoute = InventoryInboundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryInboundRoute,
} as any)
const PurchaseJapanParcelNewRoute = PurchaseJapanParcelNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchaseJapanParcelRoute,
} as any)
const PurchaseJapanParcelImportRoute =
  PurchaseJapanParcelImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => PurchaseJapanParcelRoute,
  } as any)
const PurchaseJapanParcelAccountsRoute =
  PurchaseJapanParcelAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => PurchaseJapanParcelRoute,
  } as any)
const PurchaseJapanParcelIdRoute = PurchaseJapanParcelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchaseJapanParcelRoute,
} as any)
const PurchaseDomesticImportRoute = PurchaseDomesticImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => PurchaseDomesticRoute,
} as any)
const PurchaseDomesticIdRoute = PurchaseDomesticIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchaseDomesticRoute,
} as any)
const InventorySkusIdRoute = InventorySkusIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventorySkusRoute,
} as any)
const InventoryInboundNewRoute = InventoryInboundNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryInboundRoute,
} as any)
const InventoryInboundIdRoute = InventoryInboundIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InventoryInboundRoute,
} as any)
const ApiPublicMerukiIngestRoute = ApiPublicMerukiIngestRouteImport.update({
  id: '/api/public/meruki-ingest',
  path: '/api/public/meruki-ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/inventory/batches': typeof InventoryBatchesRoute
  '/inventory/inbound': typeof InventoryInboundRouteWithChildren
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/skus': typeof InventorySkusRouteWithChildren
  '/inventory/transfers': typeof InventoryTransfersRoute
  '/purchase/domestic': typeof PurchaseDomesticRouteWithChildren
  '/purchase/japan-bulk': typeof PurchaseJapanBulkRoute
  '/purchase/japan-parcel': typeof PurchaseJapanParcelRouteWithChildren
  '/purchase/logistics': typeof PurchaseLogisticsRoute
  '/stores/franchisees': typeof StoresFranchiseesRoute
  '/stores/list': typeof StoresListRoute
  '/stores/youzan': typeof StoresYouzanRoute
  '/api/public/meruki-ingest': typeof ApiPublicMerukiIngestRoute
  '/inventory/inbound/$id': typeof InventoryInboundIdRoute
  '/inventory/inbound/new': typeof InventoryInboundNewRoute
  '/inventory/skus/$id': typeof InventorySkusIdRoute
  '/purchase/domestic/$id': typeof PurchaseDomesticIdRoute
  '/purchase/domestic/import': typeof PurchaseDomesticImportRoute
  '/purchase/japan-parcel/$id': typeof PurchaseJapanParcelIdRoute
  '/purchase/japan-parcel/accounts': typeof PurchaseJapanParcelAccountsRoute
  '/purchase/japan-parcel/import': typeof PurchaseJapanParcelImportRoute
  '/purchase/japan-parcel/new': typeof PurchaseJapanParcelNewRoute
  '/inventory/inbound/': typeof InventoryInboundIndexRoute
  '/inventory/skus/': typeof InventorySkusIndexRoute
  '/purchase/domestic/': typeof PurchaseDomesticIndexRoute
  '/purchase/japan-parcel/': typeof PurchaseJapanParcelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/inventory/batches': typeof InventoryBatchesRoute
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/transfers': typeof InventoryTransfersRoute
  '/purchase/japan-bulk': typeof PurchaseJapanBulkRoute
  '/purchase/logistics': typeof PurchaseLogisticsRoute
  '/stores/franchisees': typeof StoresFranchiseesRoute
  '/stores/list': typeof StoresListRoute
  '/stores/youzan': typeof StoresYouzanRoute
  '/api/public/meruki-ingest': typeof ApiPublicMerukiIngestRoute
  '/inventory/inbound/$id': typeof InventoryInboundIdRoute
  '/inventory/inbound/new': typeof InventoryInboundNewRoute
  '/inventory/skus/$id': typeof InventorySkusIdRoute
  '/purchase/domestic/$id': typeof PurchaseDomesticIdRoute
  '/purchase/domestic/import': typeof PurchaseDomesticImportRoute
  '/purchase/japan-parcel/$id': typeof PurchaseJapanParcelIdRoute
  '/purchase/japan-parcel/accounts': typeof PurchaseJapanParcelAccountsRoute
  '/purchase/japan-parcel/import': typeof PurchaseJapanParcelImportRoute
  '/purchase/japan-parcel/new': typeof PurchaseJapanParcelNewRoute
  '/inventory/inbound': typeof InventoryInboundIndexRoute
  '/inventory/skus': typeof InventorySkusIndexRoute
  '/purchase/domestic': typeof PurchaseDomesticIndexRoute
  '/purchase/japan-parcel': typeof PurchaseJapanParcelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/inventory/batches': typeof InventoryBatchesRoute
  '/inventory/inbound': typeof InventoryInboundRouteWithChildren
  '/inventory/products': typeof InventoryProductsRoute
  '/inventory/skus': typeof InventorySkusRouteWithChildren
  '/inventory/transfers': typeof InventoryTransfersRoute
  '/purchase/domestic': typeof PurchaseDomesticRouteWithChildren
  '/purchase/japan-bulk': typeof PurchaseJapanBulkRoute
  '/purchase/japan-parcel': typeof PurchaseJapanParcelRouteWithChildren
  '/purchase/logistics': typeof PurchaseLogisticsRoute
  '/stores/franchisees': typeof StoresFranchiseesRoute
  '/stores/list': typeof StoresListRoute
  '/stores/youzan': typeof StoresYouzanRoute
  '/api/public/meruki-ingest': typeof ApiPublicMerukiIngestRoute
  '/inventory/inbound/$id': typeof InventoryInboundIdRoute
  '/inventory/inbound/new': typeof InventoryInboundNewRoute
  '/inventory/skus/$id': typeof InventorySkusIdRoute
  '/purchase/domestic/$id': typeof PurchaseDomesticIdRoute
  '/purchase/domestic/import': typeof PurchaseDomesticImportRoute
  '/purchase/japan-parcel/$id': typeof PurchaseJapanParcelIdRoute
  '/purchase/japan-parcel/accounts': typeof PurchaseJapanParcelAccountsRoute
  '/purchase/japan-parcel/import': typeof PurchaseJapanParcelImportRoute
  '/purchase/japan-parcel/new': typeof PurchaseJapanParcelNewRoute
  '/inventory/inbound/': typeof InventoryInboundIndexRoute
  '/inventory/skus/': typeof InventorySkusIndexRoute
  '/purchase/domestic/': typeof PurchaseDomesticIndexRoute
  '/purchase/japan-parcel/': typeof PurchaseJapanParcelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/settings'
    | '/admin/users'
    | '/inventory/batches'
    | '/inventory/inbound'
    | '/inventory/products'
    | '/inventory/skus'
    | '/inventory/transfers'
    | '/purchase/domestic'
    | '/purchase/japan-bulk'
    | '/purchase/japan-parcel'
    | '/purchase/logistics'
    | '/stores/franchisees'
    | '/stores/list'
    | '/stores/youzan'
    | '/api/public/meruki-ingest'
    | '/inventory/inbound/$id'
    | '/inventory/inbound/new'
    | '/inventory/skus/$id'
    | '/purchase/domestic/$id'
    | '/purchase/domestic/import'
    | '/purchase/japan-parcel/$id'
    | '/purchase/japan-parcel/accounts'
    | '/purchase/japan-parcel/import'
    | '/purchase/japan-parcel/new'
    | '/inventory/inbound/'
    | '/inventory/skus/'
    | '/purchase/domestic/'
    | '/purchase/japan-parcel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/settings'
    | '/admin/users'
    | '/inventory/batches'
    | '/inventory/products'
    | '/inventory/transfers'
    | '/purchase/japan-bulk'
    | '/purchase/logistics'
    | '/stores/franchisees'
    | '/stores/list'
    | '/stores/youzan'
    | '/api/public/meruki-ingest'
    | '/inventory/inbound/$id'
    | '/inventory/inbound/new'
    | '/inventory/skus/$id'
    | '/purchase/domestic/$id'
    | '/purchase/domestic/import'
    | '/purchase/japan-parcel/$id'
    | '/purchase/japan-parcel/accounts'
    | '/purchase/japan-parcel/import'
    | '/purchase/japan-parcel/new'
    | '/inventory/inbound'
    | '/inventory/skus'
    | '/purchase/domestic'
    | '/purchase/japan-parcel'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/settings'
    | '/admin/users'
    | '/inventory/batches'
    | '/inventory/inbound'
    | '/inventory/products'
    | '/inventory/skus'
    | '/inventory/transfers'
    | '/purchase/domestic'
    | '/purchase/japan-bulk'
    | '/purchase/japan-parcel'
    | '/purchase/logistics'
    | '/stores/franchisees'
    | '/stores/list'
    | '/stores/youzan'
    | '/api/public/meruki-ingest'
    | '/inventory/inbound/$id'
    | '/inventory/inbound/new'
    | '/inventory/skus/$id'
    | '/purchase/domestic/$id'
    | '/purchase/domestic/import'
    | '/purchase/japan-parcel/$id'
    | '/purchase/japan-parcel/accounts'
    | '/purchase/japan-parcel/import'
    | '/purchase/japan-parcel/new'
    | '/inventory/inbound/'
    | '/inventory/skus/'
    | '/purchase/domestic/'
    | '/purchase/japan-parcel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  InventoryBatchesRoute: typeof InventoryBatchesRoute
  InventoryInboundRoute: typeof InventoryInboundRouteWithChildren
  InventoryProductsRoute: typeof InventoryProductsRoute
  InventorySkusRoute: typeof InventorySkusRouteWithChildren
  InventoryTransfersRoute: typeof InventoryTransfersRoute
  PurchaseDomesticRoute: typeof PurchaseDomesticRouteWithChildren
  PurchaseJapanBulkRoute: typeof PurchaseJapanBulkRoute
  PurchaseJapanParcelRoute: typeof PurchaseJapanParcelRouteWithChildren
  PurchaseLogisticsRoute: typeof PurchaseLogisticsRoute
  StoresFranchiseesRoute: typeof StoresFranchiseesRoute
  StoresListRoute: typeof StoresListRoute
  StoresYouzanRoute: typeof StoresYouzanRoute
  ApiPublicMerukiIngestRoute: typeof ApiPublicMerukiIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/youzan': {
      id: '/stores/youzan'
      path: '/stores/youzan'
      fullPath: '/stores/youzan'
      preLoaderRoute: typeof StoresYouzanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/list': {
      id: '/stores/list'
      path: '/stores/list'
      fullPath: '/stores/list'
      preLoaderRoute: typeof StoresListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/franchisees': {
      id: '/stores/franchisees'
      path: '/stores/franchisees'
      fullPath: '/stores/franchisees'
      preLoaderRoute: typeof StoresFranchiseesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/logistics': {
      id: '/purchase/logistics'
      path: '/purchase/logistics'
      fullPath: '/purchase/logistics'
      preLoaderRoute: typeof PurchaseLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/japan-parcel': {
      id: '/purchase/japan-parcel'
      path: '/purchase/japan-parcel'
      fullPath: '/purchase/japan-parcel'
      preLoaderRoute: typeof PurchaseJapanParcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/japan-bulk': {
      id: '/purchase/japan-bulk'
      path: '/purchase/japan-bulk'
      fullPath: '/purchase/japan-bulk'
      preLoaderRoute: typeof PurchaseJapanBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/domestic': {
      id: '/purchase/domestic'
      path: '/purchase/domestic'
      fullPath: '/purchase/domestic'
      preLoaderRoute: typeof PurchaseDomesticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/transfers': {
      id: '/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof InventoryTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/skus': {
      id: '/inventory/skus'
      path: '/inventory/skus'
      fullPath: '/inventory/skus'
      preLoaderRoute: typeof InventorySkusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/products': {
      id: '/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof InventoryProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/inbound': {
      id: '/inventory/inbound'
      path: '/inventory/inbound'
      fullPath: '/inventory/inbound'
      preLoaderRoute: typeof InventoryInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/batches': {
      id: '/inventory/batches'
      path: '/inventory/batches'
      fullPath: '/inventory/batches'
      preLoaderRoute: typeof InventoryBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/japan-parcel/': {
      id: '/purchase/japan-parcel/'
      path: '/'
      fullPath: '/purchase/japan-parcel/'
      preLoaderRoute: typeof PurchaseJapanParcelIndexRouteImport
      parentRoute: typeof PurchaseJapanParcelRoute
    }
    '/purchase/domestic/': {
      id: '/purchase/domestic/'
      path: '/'
      fullPath: '/purchase/domestic/'
      preLoaderRoute: typeof PurchaseDomesticIndexRouteImport
      parentRoute: typeof PurchaseDomesticRoute
    }
    '/inventory/skus/': {
      id: '/inventory/skus/'
      path: '/'
      fullPath: '/inventory/skus/'
      preLoaderRoute: typeof InventorySkusIndexRouteImport
      parentRoute: typeof InventorySkusRoute
    }
    '/inventory/inbound/': {
      id: '/inventory/inbound/'
      path: '/'
      fullPath: '/inventory/inbound/'
      preLoaderRoute: typeof InventoryInboundIndexRouteImport
      parentRoute: typeof InventoryInboundRoute
    }
    '/purchase/japan-parcel/new': {
      id: '/purchase/japan-parcel/new'
      path: '/new'
      fullPath: '/purchase/japan-parcel/new'
      preLoaderRoute: typeof PurchaseJapanParcelNewRouteImport
      parentRoute: typeof PurchaseJapanParcelRoute
    }
    '/purchase/japan-parcel/import': {
      id: '/purchase/japan-parcel/import'
      path: '/import'
      fullPath: '/purchase/japan-parcel/import'
      preLoaderRoute: typeof PurchaseJapanParcelImportRouteImport
      parentRoute: typeof PurchaseJapanParcelRoute
    }
    '/purchase/japan-parcel/accounts': {
      id: '/purchase/japan-parcel/accounts'
      path: '/accounts'
      fullPath: '/purchase/japan-parcel/accounts'
      preLoaderRoute: typeof PurchaseJapanParcelAccountsRouteImport
      parentRoute: typeof PurchaseJapanParcelRoute
    }
    '/purchase/japan-parcel/$id': {
      id: '/purchase/japan-parcel/$id'
      path: '/$id'
      fullPath: '/purchase/japan-parcel/$id'
      preLoaderRoute: typeof PurchaseJapanParcelIdRouteImport
      parentRoute: typeof PurchaseJapanParcelRoute
    }
    '/purchase/domestic/import': {
      id: '/purchase/domestic/import'
      path: '/import'
      fullPath: '/purchase/domestic/import'
      preLoaderRoute: typeof PurchaseDomesticImportRouteImport
      parentRoute: typeof PurchaseDomesticRoute
    }
    '/purchase/domestic/$id': {
      id: '/purchase/domestic/$id'
      path: '/$id'
      fullPath: '/purchase/domestic/$id'
      preLoaderRoute: typeof PurchaseDomesticIdRouteImport
      parentRoute: typeof PurchaseDomesticRoute
    }
    '/inventory/skus/$id': {
      id: '/inventory/skus/$id'
      path: '/$id'
      fullPath: '/inventory/skus/$id'
      preLoaderRoute: typeof InventorySkusIdRouteImport
      parentRoute: typeof InventorySkusRoute
    }
    '/inventory/inbound/new': {
      id: '/inventory/inbound/new'
      path: '/new'
      fullPath: '/inventory/inbound/new'
      preLoaderRoute: typeof InventoryInboundNewRouteImport
      parentRoute: typeof InventoryInboundRoute
    }
    '/inventory/inbound/$id': {
      id: '/inventory/inbound/$id'
      path: '/$id'
      fullPath: '/inventory/inbound/$id'
      preLoaderRoute: typeof InventoryInboundIdRouteImport
      parentRoute: typeof InventoryInboundRoute
    }
    '/api/public/meruki-ingest': {
      id: '/api/public/meruki-ingest'
      path: '/api/public/meruki-ingest'
      fullPath: '/api/public/meruki-ingest'
      preLoaderRoute: typeof ApiPublicMerukiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InventoryInboundRouteChildren {
  InventoryInboundIdRoute: typeof InventoryInboundIdRoute
  InventoryInboundNewRoute: typeof InventoryInboundNewRoute
  InventoryInboundIndexRoute: typeof InventoryInboundIndexRoute
}

const InventoryInboundRouteChildren: InventoryInboundRouteChildren = {
  InventoryInboundIdRoute: InventoryInboundIdRoute,
  InventoryInboundNewRoute: InventoryInboundNewRoute,
  InventoryInboundIndexRoute: InventoryInboundIndexRoute,
}

const InventoryInboundRouteWithChildren =
  InventoryInboundRoute._addFileChildren(InventoryInboundRouteChildren)

interface InventorySkusRouteChildren {
  InventorySkusIdRoute: typeof InventorySkusIdRoute
  InventorySkusIndexRoute: typeof InventorySkusIndexRoute
}

const InventorySkusRouteChildren: InventorySkusRouteChildren = {
  InventorySkusIdRoute: InventorySkusIdRoute,
  InventorySkusIndexRoute: InventorySkusIndexRoute,
}

const InventorySkusRouteWithChildren = InventorySkusRoute._addFileChildren(
  InventorySkusRouteChildren,
)

interface PurchaseDomesticRouteChildren {
  PurchaseDomesticIdRoute: typeof PurchaseDomesticIdRoute
  PurchaseDomesticImportRoute: typeof PurchaseDomesticImportRoute
  PurchaseDomesticIndexRoute: typeof PurchaseDomesticIndexRoute
}

const PurchaseDomesticRouteChildren: PurchaseDomesticRouteChildren = {
  PurchaseDomesticIdRoute: PurchaseDomesticIdRoute,
  PurchaseDomesticImportRoute: PurchaseDomesticImportRoute,
  PurchaseDomesticIndexRoute: PurchaseDomesticIndexRoute,
}

const PurchaseDomesticRouteWithChildren =
  PurchaseDomesticRoute._addFileChildren(PurchaseDomesticRouteChildren)

interface PurchaseJapanParcelRouteChildren {
  PurchaseJapanParcelIdRoute: typeof PurchaseJapanParcelIdRoute
  PurchaseJapanParcelAccountsRoute: typeof PurchaseJapanParcelAccountsRoute
  PurchaseJapanParcelImportRoute: typeof PurchaseJapanParcelImportRoute
  PurchaseJapanParcelNewRoute: typeof PurchaseJapanParcelNewRoute
  PurchaseJapanParcelIndexRoute: typeof PurchaseJapanParcelIndexRoute
}

const PurchaseJapanParcelRouteChildren: PurchaseJapanParcelRouteChildren = {
  PurchaseJapanParcelIdRoute: PurchaseJapanParcelIdRoute,
  PurchaseJapanParcelAccountsRoute: PurchaseJapanParcelAccountsRoute,
  PurchaseJapanParcelImportRoute: PurchaseJapanParcelImportRoute,
  PurchaseJapanParcelNewRoute: PurchaseJapanParcelNewRoute,
  PurchaseJapanParcelIndexRoute: PurchaseJapanParcelIndexRoute,
}

const PurchaseJapanParcelRouteWithChildren =
  PurchaseJapanParcelRoute._addFileChildren(PurchaseJapanParcelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  InventoryBatchesRoute: InventoryBatchesRoute,
  InventoryInboundRoute: InventoryInboundRouteWithChildren,
  InventoryProductsRoute: InventoryProductsRoute,
  InventorySkusRoute: InventorySkusRouteWithChildren,
  InventoryTransfersRoute: InventoryTransfersRoute,
  PurchaseDomesticRoute: PurchaseDomesticRouteWithChildren,
  PurchaseJapanBulkRoute: PurchaseJapanBulkRoute,
  PurchaseJapanParcelRoute: PurchaseJapanParcelRouteWithChildren,
  PurchaseLogisticsRoute: PurchaseLogisticsRoute,
  StoresFranchiseesRoute: StoresFranchiseesRoute,
  StoresListRoute: StoresListRoute,
  StoresYouzanRoute: StoresYouzanRoute,
  ApiPublicMerukiIngestRoute: ApiPublicMerukiIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
